name: Automated Crypto ETL

# The trigger: When should this robot wake up?
on:
  schedule:
    # Runs every day at 12:00 UTC (09:00 no Brasil)
    - cron: '0 12 * * *'
  # Allows you to trigger the action manually from the GitHub website
  workflow_dispatch:

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download your code to the GitHub server
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Step 3: Install the required libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      # Step 4: Run the extraction script
      - name: Execute ETL Script
        run: python main.py